#!/bin/bash

exec 3< <(egrep -o "class\sKAJ_EXPORT\s(\S+)"  ../src -R 2>&1)
#../src/game/src/movementanimation.h:class TOOJ_EXPORT MovementAnimation

pattern="\.\.\/src\/(\w+)\/src\/([a-z]+)\.h\:class\sKAJ_EXPORT\s(\w+)"

while read line; do
	if [[ $line =~ $pattern ]]; then
		dir=${BASH_REMATCH[1]}
		header=${BASH_REMATCH[2]}
		class=${BASH_REMATCH[3]}
		
		mkdir -p $dir
		echo "#include \"../src/$dir/src/$header.h\"" > $class
		echo "#include \"../../src/$dir/src/$header.h\"" > $dir/$class
	fi
done <&3
exec 3<&-
#echo "$f"
